site_name: Betty Snyder
site_url: https://fcte-qualidade-de-software-1.github.io/2025-2_T01_BETTY-SNYDER
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_BETTY-SNYDER
repo_name: Betty Snyder
site_description: Documentação do projeto do grupo Betty Snyder de Qualidade de Software (2025.2), Turma 1

strict: false

nav:
  - Início: index.md
  - Fase 1:
    - Fase 1/index.md
  - Fase 2:
    - Fase 2/index.md
  - Fase 3:
    - Fase 3/index.md
  - Fase 4:
      - Fase 4: Fase 4/index.md

      - Métricas - Manutenibilidade:
          - M1 - Grau de Modularidade (GM): Fase 4/metricas/manutenibilidade/grau-modularidade-gm.md
          - M2 - Acoplamento entre Módulos (CBO): Fase 4/metricas/manutenibilidade/acoplamento-cbo.md
          - M3 - Cobertura de Documentação (CD): Fase 4/metricas/manutenibilidade/cobertura-documentacao-cd.md
          - M4 - Código Duplicado (DUP): Fase 4/metricas/manutenibilidade/codigo-duplicado-dup.md
          - M5 - Cobertura de Testes (CTA): Fase 4/metricas/manutenibilidade/cobertura-testes-cta.md
          - M6 - Complexidade Ciclomática Média (CCM): Fase 4/metricas/manutenibilidade/complexidade-ciclomatica-ccm.md

      - Métricas - Eficiência de Desempenho:
          - M7 - Tempo Médio de Resposta (TR): Fase 4/metricas/eficiencia/tr-tempo-medio-resposta.md
          - M8 - Tempo até Primeiro Conteúdo (FCP): Fase 4/metricas/eficiencia/fcp-primeiro-conteudo.md
          - M9 - Uso de CPU (Ucpu): Fase 4/metricas/eficiencia/uso-cpu-ucpu.md
          - M10 - Uso de Memória (Umem): Fase 4/metricas/eficiencia/uso-memoria-umem.md
          - M11 - Taxa de Disponibilidade (TD): Fase 4/metricas/eficiencia/taxa-disponibilidade-td.md
    

theme:
  name: material
  language: pt-BR

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs        # Adiciona abas de navegação no topo da página
    - navigation.top         # Botão "Voltar ao topo" para facilitar navegação
    - search.suggest         # Sugestões automáticas durante a busca
    - search.highlight       # Destaca termos pesquisados nos resultados
    - navigation.sections    # Organiza navegação em seções
    - navigation.indexes     # Permite páginas de índice para seções
    - navigation.instant     # Carregamento instantâneo de páginas
    - content.tabs.link      # Vincula abas de conteúdo
    - content.code.annotate  # Permite anotações em blocos de código
    - content.code.copy      # Botão para copiar código dos blocos
    - navigation.expand      # Expande seções de navegação automaticamente
    - navigation.tracking    # Atualiza URL conforme navegação
    - header.autohide        # Esconde cabeçalho automaticamente ao fazer scroll
  
  palette: 
    # Paleta para o modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo escuro

    # Paleta para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo claro

plugins:
  - search